services:
    kafka:
        image: "bitnami/kafka:3.7-debian-12"
        restart: always
        networks:
            - kafka1
            - kafka2
        ports:
          - 29092:29092

networks:
    kafka1:
        driver: bridge
    kafka2: 
        driver: bridge
